// Kerala 2026 Election Results — generated from kerala_2026_processed.csv
// One entry per constituency, keyed by ECI constituency number (1-140)
// Margins: if NDA lost → winner_votes - NDA_votes; if NDA won → winner_votes - runner_up_votes
const KERALA_2026 = {
  "1": {
    "csvName": "Manjeshwar",
    "winnerName": "A K M Ashraf",
    "winnerParty": "Indian Union Muslim League",
    "winnerVotes": 96948,
    "loserName": "K Surendran",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 67696,
    "margin": 29252,
    "officialMargin": 29252,
    "ndaWon": false,
    "ndaCandidate": "K Surendran",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 67696,
    "ndaVotePct": 36.05,
    "totalVotes": 187801,
    "numCandidates": 11,
    "runnerUpName": "K Surendran",
    "runnerUpParty": "Bharatiya Janata Party",
    "runnerUpVotes": 67696
  },
  "2": {
    "csvName": "Kasaragod",
    "winnerName": "Kallatra Mahin",
    "winnerParty": "Indian Union Muslim League",
    "winnerVotes": 76396,
    "loserName": "Ashwini M L",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 53698,
    "margin": 22698,
    "officialMargin": 22698,
    "ndaWon": false,
    "ndaCandidate": "Ashwini M L",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 53698,
    "ndaVotePct": 31.74,
    "totalVotes": 169203,
    "numCandidates": 5,
    "runnerUpName": "Ashwini M L",
    "runnerUpParty": "Bharatiya Janata Party",
    "runnerUpVotes": 53698
  },
  "3": {
    "csvName": "Udma",
    "winnerName": "Neelakandan",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 78910,
    "loserName": "Manulal M",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 26899,
    "margin": 52011,
    "officialMargin": 4847,
    "ndaWon": false,
    "ndaCandidate": "Manulal M",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 26899,
    "ndaVotePct": 14.88,
    "totalVotes": 180816,
    "numCandidates": 6,
    "runnerUpName": "C H Kunhambu",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 74063
  },
  "4": {
    "csvName": "Kanhangad",
    "winnerName": "Adv. Govindan Pallikappil",
    "winnerParty": "Communist Party of India",
    "winnerVotes": 79920,
    "loserName": "M Balraj",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 27063,
    "margin": 52857,
    "officialMargin": 15316,
    "ndaWon": false,
    "ndaCandidate": "M Balraj",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 27063,
    "ndaVotePct": 15.4,
    "totalVotes": 175777,
    "numCandidates": 4,
    "runnerUpName": "Shaiji Ottapalli",
    "runnerUpParty": "Kerala Congress",
    "runnerUpVotes": 64604
  },
  "5": {
    "csvName": "Trikaripur",
    "winnerName": "Sandeep Varier",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 83109,
    "loserName": "Ravi Kulangara",
    "loserParty": "Twenty 20 Party",
    "loserVotes": 7837,
    "margin": 75272,
    "officialMargin": 4431,
    "ndaWon": false,
    "ndaCandidate": "Ravi Kulangara",
    "ndaParty": "Twenty 20 Party",
    "ndaVotes": 7837,
    "ndaVotePct": 4.59,
    "totalVotes": 170904,
    "numCandidates": 6,
    "runnerUpName": "Dr. V P P Mustafa",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 78678
  },
  "6": {
    "csvName": "Payyannur",
    "winnerName": "V. Kunhikrishnan",
    "winnerParty": "Independent",
    "winnerVotes": 76640,
    "loserName": "A. P. Gangadharan",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 8432,
    "margin": 68208,
    "officialMargin": 7487,
    "ndaWon": false,
    "ndaCandidate": "A. P. Gangadharan",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 8432,
    "ndaVotePct": 5.41,
    "totalVotes": 155970,
    "numCandidates": 4,
    "runnerUpName": "T. I. Madhusoodanan",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 69153
  },
  "9": {
    "csvName": "Irikkur",
    "winnerName": "Adv. Sajeev Joseph",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 90895,
    "loserName": "Sreenath Padmanabhan",
    "loserParty": "Twenty 20 Party",
    "loserVotes": 9617,
    "margin": 81278,
    "officialMargin": 42426,
    "ndaWon": false,
    "ndaCandidate": "Sreenath Padmanabhan",
    "ndaParty": "Twenty 20 Party",
    "ndaVotes": 9617,
    "ndaVotePct": 6.34,
    "totalVotes": 151645,
    "numCandidates": 6,
    "runnerUpName": "Adv. Mathew Kunnappally",
    "runnerUpParty": "Kerala Congress (M)",
    "runnerUpVotes": 48469
  },
  "8": {
    "csvName": "Taliparamba",
    "winnerName": "T K Govindan Master S/O Kunhikkannan Nambiar",
    "winnerParty": "Independent",
    "winnerVotes": 91339,
    "loserName": "N Haridas",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 16089,
    "margin": 75250,
    "officialMargin": 12551,
    "ndaWon": false,
    "ndaCandidate": "N Haridas",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 16089,
    "ndaVotePct": 8.37,
    "totalVotes": 192175,
    "numCandidates": 10,
    "runnerUpName": "P K Shyamala Teacher",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 78788
  },
  "7": {
    "csvName": "Kalliasseri",
    "winnerName": "M. Vijin",
    "winnerParty": "Communist Party of India (Marxist)",
    "winnerVotes": 81428,
    "loserName": "Sanil A V",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 13110,
    "margin": 68318,
    "officialMargin": 18433,
    "ndaWon": false,
    "ndaCandidate": "Sanil A V",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 13110,
    "ndaVotePct": 8.2,
    "totalVotes": 159867,
    "numCandidates": 5,
    "runnerUpName": "Adv. Rajeevan Kappacheri",
    "runnerUpParty": "Indian National Congress",
    "runnerUpVotes": 62995
  },
  "16": {
    "csvName": "Peravoor",
    "winnerName": "Adv. Sunny Joseph",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 76140,
    "loserName": "Paily Vathiyattu",
    "loserParty": "Bharath Dharma Jana Sena",
    "loserVotes": 8020,
    "margin": 68120,
    "officialMargin": 14453,
    "ndaWon": false,
    "ndaCandidate": "Paily Vathiyattu",
    "ndaParty": "Bharath Dharma Jana Sena",
    "ndaVotes": 8020,
    "ndaVotePct": 5.45,
    "totalVotes": 147244,
    "numCandidates": 11,
    "runnerUpName": "K K Shailaja Teacher",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 61687
  },
  "15": {
    "csvName": "Mattannur",
    "winnerName": "V K Sanoj",
    "winnerParty": "Communist Party of India (Marxist)",
    "winnerVotes": 81456,
    "loserName": "Biju Elakkuzhi",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 17815,
    "margin": 63641,
    "officialMargin": 14168,
    "ndaWon": false,
    "ndaCandidate": "Biju Elakkuzhi",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 17815,
    "ndaVotePct": 10.49,
    "totalVotes": 169858,
    "numCandidates": 6,
    "runnerUpName": "Chandran Thillankeri",
    "runnerUpParty": "Indian National Congress",
    "runnerUpVotes": 67288
  },
  "10": {
    "csvName": "Azhikode",
    "winnerName": "K. V. Sumesh",
    "winnerParty": "Communist Party of India (Marxist)",
    "winnerVotes": 64951,
    "loserName": "K. K. Vinodkumar",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 17476,
    "margin": 47475,
    "officialMargin": 349,
    "ndaWon": false,
    "ndaCandidate": "K. K. Vinodkumar",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 17476,
    "ndaVotePct": 11.78,
    "totalVotes": 148412,
    "numCandidates": 8,
    "runnerUpName": "Adv. Kareem Cheleri",
    "runnerUpParty": "Indian Union Muslim League",
    "runnerUpVotes": 64602
  },
  "17": {
    "csvName": "Mananthavady",
    "winnerName": "Usha Vijayan",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 77425,
    "loserName": "P Shyamraj",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 19681,
    "margin": 57744,
    "officialMargin": 10543,
    "ndaWon": false,
    "ndaCandidate": "P Shyamraj",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 19681,
    "ndaVotePct": 11.93,
    "totalVotes": 165006,
    "numCandidates": 3,
    "runnerUpName": "O R Kelu",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 66882
  },
  "11": {
    "csvName": "Kannur",
    "winnerName": "Adv.T.O. Mohanan",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 70620,
    "loserName": "C. Raghunath",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 16144,
    "margin": 54476,
    "officialMargin": 18551,
    "ndaWon": false,
    "ndaCandidate": "C. Raghunath",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 16144,
    "ndaVotePct": 11.49,
    "totalVotes": 140519,
    "numCandidates": 7,
    "runnerUpName": "Ramachandran Kadannappalli",
    "runnerUpParty": "Congress (Secular)",
    "runnerUpVotes": 52069
  },
  "12": {
    "csvName": "Dharmadam",
    "winnerName": "Pinarayi Vijayan",
    "winnerParty": "Communist Party of India (Marxist)",
    "winnerVotes": 85614,
    "loserName": "K. Ranjith",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 18555,
    "margin": 67059,
    "officialMargin": 19247,
    "ndaWon": false,
    "ndaCandidate": "K. Ranjith",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 18555,
    "ndaVotePct": 10.81,
    "totalVotes": 171659,
    "numCandidates": 5,
    "runnerUpName": "Adv. V.P Abdul Rasheed",
    "runnerUpParty": "Indian National Congress",
    "runnerUpVotes": 66367
  },
  "14": {
    "csvName": "Kuthuparamba",
    "winnerName": "P K Praveen",
    "winnerParty": "Rashtriya Janata Dal",
    "winnerVotes": 70448,
    "loserName": "Adv. Shijilal",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 22195,
    "margin": 48253,
    "officialMargin": 1286,
    "ndaWon": false,
    "ndaCandidate": "Adv. Shijilal",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 22195,
    "ndaVotePct": 13.52,
    "totalVotes": 164202,
    "numCandidates": 9,
    "runnerUpName": "Jayanthi Rajan",
    "runnerUpParty": "Indian Union Muslim League",
    "runnerUpVotes": 69162
  },
  "18": {
    "csvName": "Sulthanbathery",
    "winnerName": "I C Balakrishnan",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 78936,
    "loserName": "Kavitha A S",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 31308,
    "margin": 47628,
    "officialMargin": 16597,
    "ndaWon": false,
    "ndaCandidate": "Kavitha A S",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 31308,
    "ndaVotePct": 17.69,
    "totalVotes": 176938,
    "numCandidates": 8,
    "runnerUpName": "M S Viswanathan",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 62339
  },
  "13": {
    "csvName": "Thalassery",
    "winnerName": "Karayi Rajan",
    "winnerParty": "Communist Party of India (Marxist)",
    "winnerVotes": 69743,
    "loserName": "O Nidheesh",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 22754,
    "margin": 46989,
    "officialMargin": 20523,
    "ndaWon": false,
    "ndaCandidate": "O Nidheesh",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 22754,
    "ndaVotePct": 15.77,
    "totalVotes": 144287,
    "numCandidates": 7,
    "runnerUpName": "Saju K P",
    "runnerUpParty": "Indian National Congress",
    "runnerUpVotes": 49220
  },
  "22": {
    "csvName": "Nadapuram",
    "winnerName": "K.M. Abhijith",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 99763,
    "loserName": "C.P. Vipin Chandran",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 11506,
    "margin": 88257,
    "officialMargin": 23600,
    "ndaWon": false,
    "ndaCandidate": "C.P. Vipin Chandran",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 11506,
    "ndaVotePct": 6.1,
    "totalVotes": 188712,
    "numCandidates": 7,
    "runnerUpName": "Adv.P. Vasantham",
    "runnerUpParty": "Communist Party of India",
    "runnerUpVotes": 76163
  },
  "19": {
    "csvName": "Kalpetta",
    "winnerName": "Adv. T Siddique",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 97379,
    "loserName": "Prasanth Malavayal",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 19175,
    "margin": 78204,
    "officialMargin": 45031,
    "ndaWon": false,
    "ndaCandidate": "Prasanth Malavayal",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 19175,
    "ndaVotePct": 11.06,
    "totalVotes": 173441,
    "numCandidates": 10,
    "runnerUpName": "P K Anil Kumar",
    "runnerUpParty": "Rashtriya Janata Dal",
    "runnerUpVotes": 52348
  },
  "20": {
    "csvName": "Vadakara",
    "winnerName": "K K Rema",
    "winnerParty": "Revolutionary Marxist Party of India",
    "winnerVotes": 70117,
    "loserName": "Adv. K Dileep",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 14295,
    "margin": 55822,
    "officialMargin": 14862,
    "ndaWon": false,
    "ndaCandidate": "Adv. K Dileep",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 14295,
    "ndaVotePct": 9.98,
    "totalVotes": 143179,
    "numCandidates": 8,
    "runnerUpName": "M K Bhaskaran",
    "runnerUpParty": "Rashtriya Janata Dal",
    "runnerUpVotes": 55255
  },
  "21": {
    "csvName": "Kuttiadi",
    "winnerName": "Parakkal Abdulla",
    "winnerParty": "Indian Union Muslim League",
    "winnerVotes": 88197,
    "loserName": "Ramadas Manaleri",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 12035,
    "margin": 76162,
    "officialMargin": 10922,
    "ndaWon": false,
    "ndaCandidate": "Ramadas Manaleri",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 12035,
    "ndaVotePct": 6.76,
    "totalVotes": 178106,
    "numCandidates": 5,
    "runnerUpName": "K. P. Kunhammedkutty Master",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 77275
  },
  "24": {
    "csvName": "Perambra",
    "winnerName": "Adv. Fathima Thahiliya",
    "winnerParty": "Indian Union Muslim League",
    "winnerVotes": 81429,
    "loserName": "M. Mohanan Master",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 13042,
    "margin": 68387,
    "officialMargin": 5087,
    "ndaWon": false,
    "ndaCandidate": "M. Mohanan Master",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 13042,
    "ndaVotePct": 7.58,
    "totalVotes": 172086,
    "numCandidates": 10,
    "runnerUpName": "T. P. Ramakrishnan",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 76342
  },
  "25": {
    "csvName": "Balusseri",
    "winnerName": "V.T. Sooraj",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 94804,
    "loserName": "C.P. Satheesh",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 17669,
    "margin": 77135,
    "officialMargin": 16980,
    "ndaWon": false,
    "ndaCandidate": "C.P. Satheesh",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 17669,
    "ndaVotePct": 9.24,
    "totalVotes": 191315,
    "numCandidates": 5,
    "runnerUpName": "Adv. K.M. Sachindev",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 77824
  },
  "23": {
    "csvName": "Quilandy",
    "winnerName": "Adv. K. Praveen Kumar",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 79913,
    "loserName": "Praful Krishnan",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 23545,
    "margin": 56368,
    "officialMargin": 12070,
    "ndaWon": false,
    "ndaCandidate": "Praful Krishnan",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 23545,
    "ndaVotePct": 13.66,
    "totalVotes": 172425,
    "numCandidates": 7,
    "runnerUpName": "K. Dasan",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 67843
  },
  "31": {
    "csvName": "Koduvally",
    "winnerName": "P K Firos",
    "winnerParty": "Indian Union Muslim League",
    "winnerVotes": 95164,
    "loserName": "Giri Pambanal",
    "loserParty": "Bharath Dharma Jana Sena",
    "loserVotes": 9832,
    "margin": 85332,
    "officialMargin": 36682,
    "ndaWon": false,
    "ndaCandidate": "Giri Pambanal",
    "ndaParty": "Bharath Dharma Jana Sena",
    "ndaVotes": 9832,
    "ndaVotePct": 5.92,
    "totalVotes": 165988,
    "numCandidates": 13,
    "runnerUpName": "Saleem Madavoor",
    "runnerUpParty": "Independent",
    "runnerUpVotes": 58482
  },
  "32": {
    "csvName": "Thiruvambadi",
    "winnerName": "C K Kasim",
    "winnerParty": "Indian Union Muslim League",
    "winnerVotes": 77140,
    "loserName": "Sunny Thomas",
    "loserParty": "Twenty 20 Party",
    "loserVotes": 7380,
    "margin": 69760,
    "officialMargin": 6741,
    "ndaWon": false,
    "ndaCandidate": "Sunny Thomas",
    "ndaParty": "Twenty 20 Party",
    "ndaVotes": 7380,
    "ndaVotePct": 4.71,
    "totalVotes": 156680,
    "numCandidates": 7,
    "runnerUpName": "Linto Joseph",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 70399
  },
  "35": {
    "csvName": "Nilambur",
    "winnerName": "Aryadan Shoukath",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 113586,
    "loserName": "Girish Mekkattu",
    "loserParty": "Bharath Dharma Jana Sena",
    "loserVotes": 12660,
    "margin": 100926,
    "officialMargin": 54851,
    "ndaWon": false,
    "ndaCandidate": "Girish Mekkattu",
    "ndaParty": "Bharath Dharma Jana Sena",
    "ndaVotes": 12660,
    "ndaVotePct": 6.68,
    "totalVotes": 189595,
    "numCandidates": 4,
    "runnerUpName": "U Sharafali",
    "runnerUpParty": "Independent",
    "runnerUpVotes": 58735
  },
  "26": {
    "csvName": "Elathur",
    "winnerName": "Adv.Vidya Balakrishnan",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 77662,
    "loserName": "Devadas T",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 31510,
    "margin": 46152,
    "officialMargin": 12162,
    "ndaWon": false,
    "ndaCandidate": "Devadas T",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 31510,
    "ndaVotePct": 17.73,
    "totalVotes": 177765,
    "numCandidates": 8,
    "runnerUpName": "A.K.Saseendran S/O Kunjambu",
    "runnerUpParty": "Nationalist Congress Party - Sharadchandra Pawar",
    "runnerUpVotes": 65500
  },
  "34": {
    "csvName": "Ernad",
    "winnerName": "P.K.Basheer",
    "winnerParty": "Indian Union Muslim League",
    "winnerVotes": 98547,
    "loserName": "Adv.N.Sreeprakash",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 8728,
    "margin": 89819,
    "officialMargin": 41289,
    "ndaWon": false,
    "ndaCandidate": "Adv.N.Sreeprakash",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 8728,
    "ndaVotePct": 5.17,
    "totalVotes": 168681,
    "numCandidates": 6,
    "runnerUpName": "Adv.Shafeer Kizhisseri",
    "runnerUpParty": "Communist Party of India",
    "runnerUpVotes": 57258
  },
  "30": {
    "csvName": "Kunnamangalam",
    "winnerName": "M.A. Razak Master",
    "winnerParty": "Indian Union Muslim League",
    "winnerVotes": 91598,
    "loserName": "Adv.V. K. Sajeevan",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 34435,
    "margin": 57163,
    "officialMargin": 13313,
    "ndaWon": false,
    "ndaCandidate": "Adv.V. K. Sajeevan",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 34435,
    "ndaVotePct": 16.48,
    "totalVotes": 208949,
    "numCandidates": 9,
    "runnerUpName": "Adv. P T A Rahim",
    "runnerUpParty": "Independent",
    "runnerUpVotes": 78285
  },
  "27": {
    "csvName": "Kozhikode North",
    "winnerName": "Adv.K Jayanth",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 50636,
    "loserName": "Navya Haridas",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 39899,
    "margin": 10737,
    "officialMargin": 1483,
    "ndaWon": false,
    "ndaCandidate": "Navya Haridas",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 39899,
    "ndaVotePct": 28.19,
    "totalVotes": 141535,
    "numCandidates": 10,
    "runnerUpName": "Thottathil Ravindran",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 49153
  },
  "28": {
    "csvName": "Kozhikode South",
    "winnerName": "Adv. Fyzal Babu",
    "winnerParty": "Indian Union Muslim League",
    "winnerVotes": 52680,
    "loserName": "T. Raneesh",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 32463,
    "margin": 20217,
    "officialMargin": 10795,
    "ndaWon": false,
    "ndaCandidate": "T. Raneesh",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 32463,
    "ndaVotePct": 25.39,
    "totalVotes": 127866,
    "numCandidates": 3,
    "runnerUpName": "Ahammad Devarkovil",
    "runnerUpParty": "Indian National League",
    "runnerUpVotes": 41885
  },
  "33": {
    "csvName": "Kondotty",
    "winnerName": "T.P. Ashrafali",
    "winnerParty": "Indian Union Muslim League",
    "winnerVotes": 114997,
    "loserName": "P. Subrahmannian",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 13994,
    "margin": 101003,
    "officialMargin": 56017,
    "ndaWon": false,
    "ndaCandidate": "P. Subrahmannian",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 13994,
    "ndaVotePct": 7.3,
    "totalVotes": 191625,
    "numCandidates": 5,
    "runnerUpName": "Dr. P. Jiji",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 58980
  },
  "36": {
    "csvName": "Wandoor",
    "winnerName": "A.P Anilkumar",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 121074,
    "loserName": "",
    "loserParty": "",
    "loserVotes": 0,
    "margin": 0,
    "officialMargin": 47939,
    "ndaWon": false,
    "ndaCandidate": "",
    "ndaParty": "",
    "ndaVotes": 0,
    "ndaVotePct": 0.0,
    "totalVotes": 203168,
    "numCandidates": 4,
    "runnerUpName": "Dr.K.K Damodaran",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 73135
  },
  "29": {
    "csvName": "Beypore",
    "winnerName": "P.A Mohamed Riyas",
    "winnerParty": "Communist Party of India (Marxist)",
    "winnerVotes": 81849,
    "loserName": "Adv. Prakashbabu",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 26543,
    "margin": 55306,
    "officialMargin": 7487,
    "ndaWon": false,
    "ndaCandidate": "Adv. Prakashbabu",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 26543,
    "ndaVotePct": 14.34,
    "totalVotes": 185150,
    "numCandidates": 8,
    "runnerUpName": "P V Anvar S/O Shoukathali",
    "runnerUpParty": "Independent",
    "runnerUpVotes": 74362
  },
  "54": {
    "csvName": "Mannarkkad",
    "winnerName": "Adv. N. Samsudheen",
    "winnerParty": "Indian Union Muslim League",
    "winnerVotes": 90606,
    "loserName": "Issac Varghese",
    "loserParty": "Bharath Dharma Jana Sena",
    "loserVotes": 10671,
    "margin": 79935,
    "officialMargin": 25903,
    "ndaWon": false,
    "ndaCandidate": "Issac Varghese",
    "ndaParty": "Bharath Dharma Jana Sena",
    "ndaVotes": 10671,
    "ndaVotePct": 6.32,
    "totalVotes": 168781,
    "numCandidates": 7,
    "runnerUpName": "Manzil Aboobacker",
    "runnerUpParty": "Communist Party of India",
    "runnerUpVotes": 64703
  },
  "37": {
    "csvName": "Manjeri",
    "winnerName": "Adv. M. Rahmathulla",
    "winnerParty": "Indian Union Muslim League",
    "winnerVotes": 113622,
    "loserName": "Padmasree Ajith",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 13423,
    "margin": 100199,
    "officialMargin": 57887,
    "ndaWon": false,
    "ndaCandidate": "Padmasree Ajith",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 13423,
    "ndaVotePct": 7.06,
    "totalVotes": 190019,
    "numCandidates": 5,
    "runnerUpName": "V.M. Musthafa",
    "runnerUpParty": "Independent",
    "runnerUpVotes": 55735
  },
  "40": {
    "csvName": "Malappuram",
    "winnerName": "P.K Kunhalikutty",
    "winnerParty": "Indian Union Muslim League",
    "winnerVotes": 131632,
    "loserName": "Aswathi Gupthakumar",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 9127,
    "margin": 122505,
    "officialMargin": 85327,
    "ndaWon": false,
    "ndaCandidate": "Aswathi Gupthakumar",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 9127,
    "ndaVotePct": 4.64,
    "totalVotes": 196885,
    "numCandidates": 8,
    "runnerUpName": "K.T. Mujeeb Rahman",
    "runnerUpParty": "Nationalist Congress Party - Sharadchandra Pawar",
    "runnerUpVotes": 46305
  },
  "42": {
    "csvName": "Vallikunnu",
    "winnerName": "T V Ibrahim",
    "winnerParty": "Indian Union Muslim League",
    "winnerVotes": 100718,
    "loserName": "Premkumar (Preman Master)",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 23283,
    "margin": 77435,
    "officialMargin": 51289,
    "ndaWon": false,
    "ndaCandidate": "Premkumar (Preman Master)",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 23283,
    "ndaVotePct": 12.86,
    "totalVotes": 181022,
    "numCandidates": 6,
    "runnerUpName": "Adv. Musthafa",
    "runnerUpParty": "Independent",
    "runnerUpVotes": 49429
  },
  "41": {
    "csvName": "Vengara",
    "winnerName": "K.M. Shaji",
    "winnerParty": "Indian Union Muslim League",
    "winnerVotes": 95863,
    "loserName": "Jayakrishnan. V.N",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 6126,
    "margin": 89737,
    "officialMargin": 30325,
    "ndaWon": false,
    "ndaCandidate": "Jayakrishnan. V.N",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 6126,
    "ndaVotePct": 3.6,
    "totalVotes": 170289,
    "numCandidates": 6,
    "runnerUpName": "Sabah Kundupuzhakkal",
    "runnerUpParty": "Independent",
    "runnerUpVotes": 65538
  },
  "43": {
    "csvName": "Tirurangadi",
    "winnerName": "P M A Sameer",
    "winnerParty": "Indian Union Muslim League",
    "winnerVotes": 111869,
    "loserName": "Riju C Raghav",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 11497,
    "margin": 100372,
    "officialMargin": 63387,
    "ndaWon": false,
    "ndaCandidate": "Riju C Raghav",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 11497,
    "ndaVotePct": 6.52,
    "totalVotes": 176214,
    "numCandidates": 5,
    "runnerUpName": "Ajith Koladi",
    "runnerUpParty": "Communist Party of India",
    "runnerUpVotes": 48482
  },
  "39": {
    "csvName": "Mankada",
    "winnerName": "Manjalamkuzhi Ali",
    "winnerParty": "Indian Union Muslim League",
    "winnerVotes": 110692,
    "loserName": "Lejoy Mash",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 9933,
    "margin": 100759,
    "officialMargin": 45609,
    "ndaWon": false,
    "ndaCandidate": "Lejoy Mash",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 9933,
    "ndaVotePct": 5.29,
    "totalVotes": 187686,
    "numCandidates": 4,
    "runnerUpName": "Kunnath Mohamed S/O Ali Haji",
    "runnerUpParty": "Independent",
    "runnerUpVotes": 65083
  },
  "38": {
    "csvName": "Perinthalmanna",
    "winnerName": "Najeeb Kanthapuram",
    "winnerParty": "Indian Union Muslim League",
    "winnerVotes": 104888,
    "loserName": "Adv. K.P Baburaj",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 7240,
    "margin": 97648,
    "officialMargin": 32431,
    "ndaWon": false,
    "ndaCandidate": "Adv. K.P Baburaj",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 7240,
    "ndaVotePct": 3.89,
    "totalVotes": 186088,
    "numCandidates": 8,
    "runnerUpName": "V.P Mohammed Haneefa",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 72457
  },
  "46": {
    "csvName": "Kottakkal",
    "winnerName": "Prof. Abid Hussain Thangal",
    "winnerParty": "Indian Union Muslim League",
    "winnerVotes": 118111,
    "loserName": "Subramannian C",
    "loserParty": "Bharath Dharma Jana Sena",
    "loserVotes": 10558,
    "margin": 107553,
    "officialMargin": 62638,
    "ndaWon": false,
    "ndaCandidate": "Subramannian C",
    "ndaParty": "Bharath Dharma Jana Sena",
    "ndaVotes": 10558,
    "ndaVotePct": 5.52,
    "totalVotes": 191211,
    "numCandidates": 6,
    "runnerUpName": "Preethi Konchath",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 55473
  },
  "44": {
    "csvName": "Tanur",
    "winnerName": "P K Navas",
    "winnerParty": "Indian Union Muslim League",
    "winnerVotes": 91992,
    "loserName": "Deepa Puzhakkal",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 13642,
    "margin": 78350,
    "officialMargin": 27131,
    "ndaWon": false,
    "ndaCandidate": "Deepa Puzhakkal",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 13642,
    "ndaVotePct": 7.92,
    "totalVotes": 172324,
    "numCandidates": 6,
    "runnerUpName": "Mohamed Sameer T Thiruthiyil House",
    "runnerUpParty": "Independent",
    "runnerUpVotes": 64861
  },
  "53": {
    "csvName": "Kongad",
    "winnerName": "Thulasi Teacher",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 62734,
    "loserName": "Dr. Renu Suresh",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 24925,
    "margin": 37809,
    "officialMargin": 3706,
    "ndaWon": false,
    "ndaCandidate": "Dr. Renu Suresh",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 24925,
    "ndaVotePct": 16.77,
    "totalVotes": 148655,
    "numCandidates": 4,
    "runnerUpName": "Adv. K.Santhakumari",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 59028
  },
  "45": {
    "csvName": "Tirur",
    "winnerName": "Kurukkoli Moideen",
    "winnerParty": "Indian Union Muslim League",
    "winnerVotes": 106108,
    "loserName": "K.Narayanan Master",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 8634,
    "margin": 97474,
    "officialMargin": 24137,
    "ndaWon": false,
    "ndaCandidate": "K.Narayanan Master",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 8634,
    "ndaVotePct": 4.35,
    "totalVotes": 198509,
    "numCandidates": 9,
    "runnerUpName": "V.Abdurahiman",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 81971
  },
  "52": {
    "csvName": "Ottappalam",
    "winnerName": "Adv. K. Premkumar",
    "winnerParty": "Communist Party of India (Marxist)",
    "winnerVotes": 75362,
    "loserName": "Major Ravi",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 42476,
    "margin": 32886,
    "officialMargin": 26777,
    "ndaWon": false,
    "ndaCandidate": "Major Ravi",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 42476,
    "ndaVotePct": 24.97,
    "totalVotes": 170104,
    "numCandidates": 6,
    "runnerUpName": "P.K Sasi P.K.S S/O Padmini Amma",
    "runnerUpParty": "Independent",
    "runnerUpVotes": 48585
  },
  "51": {
    "csvName": "Shornur",
    "winnerName": "P.Mammikutty",
    "winnerParty": "Communist Party of India (Marxist)",
    "winnerVotes": 70583,
    "loserName": "Adv. Sanku.T.Das",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 33264,
    "margin": 37319,
    "officialMargin": 16517,
    "ndaWon": false,
    "ndaCandidate": "Adv. Sanku.T.Das",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 33264,
    "ndaVotePct": 20.77,
    "totalVotes": 160123,
    "numCandidates": 4,
    "runnerUpName": "P.Harigovindan",
    "runnerUpParty": "Indian National Congress",
    "runnerUpVotes": 54066
  },
  "50": {
    "csvName": "Pattambi",
    "winnerName": "Muhammed Muhassin",
    "winnerParty": "Communist Party of India",
    "winnerVotes": 80062,
    "loserName": "Adv. P. Manoj",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 15282,
    "margin": 64780,
    "officialMargin": 9442,
    "ndaWon": false,
    "ndaCandidate": "Adv. P. Manoj",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 15282,
    "ndaVotePct": 9.02,
    "totalVotes": 169436,
    "numCandidates": 7,
    "runnerUpName": "T. P. Shaji",
    "runnerUpParty": "Indian National Congress",
    "runnerUpVotes": 70620
  },
  "55": {
    "csvName": "Malampuzha",
    "winnerName": "A Prabhakaran",
    "winnerParty": "Communist Party of India (Marxist)",
    "winnerVotes": 68629,
    "loserName": "C Krishnakumar",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 48908,
    "margin": 19721,
    "officialMargin": 19721,
    "ndaWon": false,
    "ndaCandidate": "C Krishnakumar",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 48908,
    "ndaVotePct": 30.13,
    "totalVotes": 162305,
    "numCandidates": 6,
    "runnerUpName": "C Krishnakumar",
    "runnerUpParty": "Bharatiya Janata Party",
    "runnerUpVotes": 48908
  },
  "47": {
    "csvName": "Thavanur",
    "winnerName": "Adv. V S Joy",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 79661,
    "loserName": "Ravi Thelath",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 16039,
    "margin": 63622,
    "officialMargin": 14647,
    "ndaWon": false,
    "ndaCandidate": "Ravi Thelath",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 16039,
    "ndaVotePct": 9.79,
    "totalVotes": 163886,
    "numCandidates": 5,
    "runnerUpName": "Dr. K T Jaleel",
    "runnerUpParty": "Independent",
    "runnerUpVotes": 65014
  },
  "49": {
    "csvName": "Thrithala",
    "winnerName": "V T Balram",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 76427,
    "loserName": "V Unnikrishnan Master",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 15051,
    "margin": 61376,
    "officialMargin": 8385,
    "ndaWon": false,
    "ndaCandidate": "V Unnikrishnan Master",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 15051,
    "ndaVotePct": 9.28,
    "totalVotes": 162186,
    "numCandidates": 9,
    "runnerUpName": "M B Rajesh",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 68042
  },
  "48": {
    "csvName": "Ponnani",
    "winnerName": "K.P Noushad Ali",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 80674,
    "loserName": "Maneesh Janakeeyam",
    "loserParty": "Bharath Dharma Jana Sena",
    "loserVotes": 10210,
    "margin": 70464,
    "officialMargin": 13267,
    "ndaWon": false,
    "ndaCandidate": "Maneesh Janakeeyam",
    "ndaParty": "Bharath Dharma Jana Sena",
    "ndaVotes": 10210,
    "ndaVotePct": 6.3,
    "totalVotes": 161973,
    "numCandidates": 8,
    "runnerUpName": "Adv.M.K Sakkeer",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 67407
  },
  "58": {
    "csvName": "Chittur",
    "winnerName": "Adv. Sumesh Achuthan",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 65325,
    "loserName": "Pranesh Rajendran",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 14697,
    "margin": 50628,
    "officialMargin": 6510,
    "ndaWon": false,
    "ndaCandidate": "Pranesh Rajendran",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 14697,
    "ndaVotePct": 9.94,
    "totalVotes": 147788,
    "numCandidates": 6,
    "runnerUpName": "Adv. V. Murugadas",
    "runnerUpParty": "Indian Socialist Janata Dal",
    "runnerUpVotes": 58815
  },
  "56": {
    "csvName": "Palakkad",
    "winnerName": "Ramesh Pisharody",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 62199,
    "loserName": "Sobha Surendran",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 49052,
    "margin": 13147,
    "officialMargin": 13147,
    "ndaWon": false,
    "ndaCandidate": "Sobha Surendran",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 49052,
    "ndaVotePct": 33.33,
    "totalVotes": 147192,
    "numCandidates": 7,
    "runnerUpName": "Sobha Surendran",
    "runnerUpParty": "Bharatiya Janata Party",
    "runnerUpVotes": 49052
  },
  "61": {
    "csvName": "Chelakkara",
    "winnerName": "U R Pradeep",
    "winnerParty": "Communist Party of India (Marxist)",
    "winnerVotes": 76073,
    "loserName": "K Balakrishnan",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 37286,
    "margin": 38787,
    "officialMargin": 29386,
    "ndaWon": false,
    "ndaCandidate": "K Balakrishnan",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 37286,
    "ndaVotePct": 22.85,
    "totalVotes": 163151,
    "numCandidates": 5,
    "runnerUpName": "Sivadasan (Sivan Veettikunnu)",
    "runnerUpParty": "Independent",
    "runnerUpVotes": 46687
  },
  "57": {
    "csvName": "Tarur",
    "winnerName": "Sumod",
    "winnerParty": "Communist Party of India (Marxist)",
    "winnerVotes": 60557,
    "loserName": "Sureshbabu M",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 21162,
    "margin": 39395,
    "officialMargin": 11910,
    "ndaWon": false,
    "ndaCandidate": "Sureshbabu M",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 21162,
    "ndaVotePct": 16.0,
    "totalVotes": 132246,
    "numCandidates": 4,
    "runnerUpName": "Subramanian K C",
    "runnerUpParty": "Indian National Congress",
    "runnerUpVotes": 48647
  },
  "62": {
    "csvName": "Kunnamkulam",
    "winnerName": "A C Moideen",
    "winnerParty": "Communist Party of India (Marxist)",
    "winnerVotes": 69522,
    "loserName": "K R Rajin",
    "loserParty": "Bharath Dharma Jana Sena",
    "loserVotes": 17104,
    "margin": 52418,
    "officialMargin": 4563,
    "ndaWon": false,
    "ndaCandidate": "K R Rajin",
    "ndaParty": "Bharath Dharma Jana Sena",
    "ndaVotes": 17104,
    "ndaVotePct": 11.13,
    "totalVotes": 153735,
    "numCandidates": 4,
    "runnerUpName": "P T Ajay Mohan",
    "runnerUpParty": "Indian National Congress",
    "runnerUpVotes": 64959
  },
  "60": {
    "csvName": "Alathur",
    "winnerName": "T M Sasi",
    "winnerParty": "Communist Party of India (Marxist)",
    "winnerVotes": 61564,
    "loserName": "K V Prasannakumar",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 17347,
    "margin": 44217,
    "officialMargin": 8553,
    "ndaWon": false,
    "ndaCandidate": "K V Prasannakumar",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 17347,
    "ndaVotePct": 12.92,
    "totalVotes": 134229,
    "numCandidates": 5,
    "runnerUpName": "K M Febin",
    "runnerUpParty": "Indian National Congress",
    "runnerUpVotes": 53011
  },
  "63": {
    "csvName": "Guruvayoor",
    "winnerName": "N. K. Akbar",
    "winnerParty": "Communist Party of India (Marxist)",
    "winnerVotes": 66069,
    "loserName": "Adv. B. Gopalakrishnan",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 28947,
    "margin": 37122,
    "officialMargin": 1998,
    "ndaWon": false,
    "ndaCandidate": "Adv. B. Gopalakrishnan",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 28947,
    "ndaVotePct": 17.86,
    "totalVotes": 162039,
    "numCandidates": 6,
    "runnerUpName": "C. H. Rasheed",
    "runnerUpParty": "Indian Union Muslim League",
    "runnerUpVotes": 64071
  },
  "65": {
    "csvName": "Wadakkanchery",
    "winnerName": "Xavier Chittilappilly",
    "winnerParty": "Communist Party of India (Marxist)",
    "winnerVotes": 70725,
    "loserName": "Adv. T.S Ullas Babu",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 25844,
    "margin": 44881,
    "officialMargin": 5690,
    "ndaWon": false,
    "ndaCandidate": "Adv. T.S Ullas Babu",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 25844,
    "ndaVotePct": 15.79,
    "totalVotes": 163634,
    "numCandidates": 5,
    "runnerUpName": "P.N. Vaisakh",
    "runnerUpParty": "Indian National Congress",
    "runnerUpVotes": 65035
  },
  "59": {
    "csvName": "Nemmara",
    "winnerName": "K Preman",
    "winnerParty": "Communist Party of India (Marxist)",
    "winnerVotes": 66521,
    "loserName": "A.N.Anurag",
    "loserParty": "Bharath Dharma Jana Sena",
    "loserVotes": 18107,
    "margin": 48414,
    "officialMargin": 3305,
    "ndaWon": false,
    "ndaCandidate": "A.N.Anurag",
    "ndaParty": "Bharath Dharma Jana Sena",
    "ndaVotes": 18107,
    "ndaVotePct": 12.03,
    "totalVotes": 150497,
    "numCandidates": 6,
    "runnerUpName": "A. Thankappan",
    "runnerUpParty": "Indian National Congress",
    "runnerUpVotes": 63216
  },
  "64": {
    "csvName": "Manalur",
    "winnerName": "Prof C Ravindranath",
    "winnerParty": "Communist Party of India (Marxist)",
    "winnerVotes": 65337,
    "loserName": "Adv K K Aneeshkumar",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 38125,
    "margin": 27212,
    "officialMargin": 126,
    "ndaWon": false,
    "ndaCandidate": "Adv K K Aneeshkumar",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 38125,
    "ndaVotePct": 22.24,
    "totalVotes": 171387,
    "numCandidates": 10,
    "runnerUpName": "T N Prathapan",
    "runnerUpParty": "Indian National Congress",
    "runnerUpVotes": 65211
  },
  "66": {
    "csvName": "Ollur",
    "winnerName": "K Rajan",
    "winnerParty": "Communist Party of India",
    "winnerVotes": 69703,
    "loserName": "Bijoy Thomas",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 19737,
    "margin": 49966,
    "officialMargin": 8884,
    "ndaWon": false,
    "ndaCandidate": "Bijoy Thomas",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 19737,
    "ndaVotePct": 12.99,
    "totalVotes": 151990,
    "numCandidates": 5,
    "runnerUpName": "Adv. Shaji J Kodankandath",
    "runnerUpParty": "Indian National Congress",
    "runnerUpVotes": 60819
  },
  "67": {
    "csvName": "Thrissur",
    "winnerName": "Rajan. J. Pallan",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 60290,
    "loserName": "Padmaja Venugopal",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 28662,
    "margin": 31628,
    "officialMargin": 26803,
    "ndaWon": false,
    "ndaCandidate": "Padmaja Venugopal",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 28662,
    "ndaVotePct": 23.08,
    "totalVotes": 124182,
    "numCandidates": 7,
    "runnerUpName": "Alankode Leelakrishnan",
    "runnerUpParty": "Communist Party of India",
    "runnerUpVotes": 33487
  },
  "68": {
    "csvName": "Nattika",
    "winnerName": "Geethagopi",
    "winnerParty": "Communist Party of India",
    "winnerVotes": 58979,
    "loserName": "C.C. Mukundan",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 45216,
    "margin": 13763,
    "officialMargin": 7093,
    "ndaWon": false,
    "ndaCandidate": "C.C. Mukundan",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 45216,
    "ndaVotePct": 28.7,
    "totalVotes": 157535,
    "numCandidates": 3,
    "runnerUpName": "Adv. Sunil Laloor",
    "runnerUpParty": "Indian National Congress",
    "runnerUpVotes": 51886
  },
  "71": {
    "csvName": "Pudukkad",
    "winnerName": "K K Ramachandran",
    "winnerParty": "Communist Party of India (Marxist)",
    "winnerVotes": 63136,
    "loserName": "Parameswaran A (Nagesh)",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 28018,
    "margin": 35118,
    "officialMargin": 2853,
    "ndaWon": false,
    "ndaCandidate": "Parameswaran A (Nagesh)",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 28018,
    "ndaVotePct": 18.17,
    "totalVotes": 154161,
    "numCandidates": 6,
    "runnerUpName": "K M Baburajan",
    "runnerUpParty": "Indian National Congress",
    "runnerUpVotes": 60283
  },
  "72": {
    "csvName": "Chalakudy",
    "winnerName": "Saneeshkumar Joseph",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 71202,
    "loserName": "Adv. Charlypaul",
    "loserParty": "Twenty 20 Party",
    "loserVotes": 16030,
    "margin": 55172,
    "officialMargin": 23156,
    "ndaWon": false,
    "ndaCandidate": "Adv. Charlypaul",
    "ndaParty": "Twenty 20 Party",
    "ndaVotes": 16030,
    "ndaVotePct": 11.62,
    "totalVotes": 137931,
    "numCandidates": 7,
    "runnerUpName": "Adv. Biju S Chirayath",
    "runnerUpParty": "Kerala Congress (M)",
    "runnerUpVotes": 48046
  },
  "70": {
    "csvName": "Irinjalakuda",
    "winnerName": "Adv. Thomas Unniyadan",
    "winnerParty": "Kerala Congress",
    "winnerVotes": 66282,
    "loserName": "Santhosh Cherakulam",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 27167,
    "margin": 39115,
    "officialMargin": 10212,
    "ndaWon": false,
    "ndaCandidate": "Santhosh Cherakulam",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 27167,
    "ndaVotePct": 17.84,
    "totalVotes": 152241,
    "numCandidates": 7,
    "runnerUpName": "Dr.R.Bindu",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 56070
  },
  "69": {
    "csvName": "Kaipamangalam",
    "winnerName": "K.K. Valsaraj",
    "winnerParty": "Communist Party of India",
    "winnerVotes": 65448,
    "loserName": "Athulliaghosh Vettiyattil",
    "loserParty": "Bharath Dharma Jana Sena",
    "loserVotes": 19688,
    "margin": 45760,
    "officialMargin": 9944,
    "ndaWon": false,
    "ndaCandidate": "Athulliaghosh Vettiyattil",
    "ndaParty": "Bharath Dharma Jana Sena",
    "ndaVotes": 19688,
    "ndaVotePct": 13.78,
    "totalVotes": 142854,
    "numCandidates": 6,
    "runnerUpName": "T.M. Nazar",
    "runnerUpParty": "Indian National Congress",
    "runnerUpVotes": 55504
  },
  "88": {
    "csvName": "Devikulam",
    "winnerName": "F. Raja",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 50590,
    "loserName": "S.Rajendran",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 15032,
    "margin": 35558,
    "officialMargin": 5233,
    "ndaWon": false,
    "ndaCandidate": "S.Rajendran",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 15032,
    "ndaVotePct": 13.41,
    "totalVotes": 112135,
    "numCandidates": 6,
    "runnerUpName": "Adv. A. Raja",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 45357
  },
  "73": {
    "csvName": "Kodungallur",
    "winnerName": "Adv. O J Janeesh",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 65162,
    "loserName": "Dr. Varghese George",
    "loserParty": "Twenty 20 Party",
    "loserVotes": 23933,
    "margin": 41229,
    "officialMargin": 8308,
    "ndaWon": false,
    "ndaCandidate": "Dr. Varghese George",
    "ndaParty": "Twenty 20 Party",
    "ndaVotes": 23933,
    "ndaVotePct": 16.18,
    "totalVotes": 147912,
    "numCandidates": 6,
    "runnerUpName": "Adv. V R Sunil Kumar",
    "runnerUpParty": "Communist Party of India",
    "runnerUpVotes": 56854
  },
  "75": {
    "csvName": "Angamaly",
    "winnerName": "Roji M John",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 78331,
    "loserName": "Promy Kuriakose",
    "loserParty": "Twenty 20 Party",
    "loserVotes": 9893,
    "margin": 68438,
    "officialMargin": 37008,
    "ndaWon": false,
    "ndaCandidate": "Promy Kuriakose",
    "ndaParty": "Twenty 20 Party",
    "ndaVotes": 9893,
    "ndaVotePct": 7.56,
    "totalVotes": 130848,
    "numCandidates": 7,
    "runnerUpName": "Saju Paul",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 41323
  },
  "78": {
    "csvName": "Paravur",
    "winnerName": "Adv.V.D.Satheesan",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 78658,
    "loserName": "Valsala Prasannakumar",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 20377,
    "margin": 58281,
    "officialMargin": 20600,
    "ndaWon": false,
    "ndaCandidate": "Valsala Prasannakumar",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 20377,
    "ndaVotePct": 12.77,
    "totalVotes": 159555,
    "numCandidates": 7,
    "runnerUpName": "E.T.Taison Master",
    "runnerUpParty": "Communist Party of India",
    "runnerUpVotes": 58058
  },
  "79": {
    "csvName": "Vypen",
    "winnerName": "Tony Chammany",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 66112,
    "loserName": "Anitha Thomas",
    "loserParty": "Twenty 20 Party",
    "loserVotes": 13637,
    "margin": 52475,
    "officialMargin": 15648,
    "ndaWon": false,
    "ndaCandidate": "Anitha Thomas",
    "ndaParty": "Twenty 20 Party",
    "ndaVotes": 13637,
    "ndaVotePct": 10.35,
    "totalVotes": 131761,
    "numCandidates": 6,
    "runnerUpName": "Adv. M. B. Shyni",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 50464
  },
  "76": {
    "csvName": "Aluva",
    "winnerName": "Anwar Sadath",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 83899,
    "loserName": "M.A.Brahmaraj",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 18732,
    "margin": 65167,
    "officialMargin": 29143,
    "ndaWon": false,
    "ndaCandidate": "M.A.Brahmaraj",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 18732,
    "ndaVotePct": 11.78,
    "totalVotes": 158962,
    "numCandidates": 4,
    "runnerUpName": "Advocate A.M.Ariff",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 54756
  },
  "74": {
    "csvName": "Perumbavoor",
    "winnerName": "Manoj Moothedan",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 75088,
    "loserName": "Jibi Pathickal",
    "loserParty": "Twenty 20 Party",
    "loserVotes": 22497,
    "margin": 52591,
    "officialMargin": 28434,
    "ndaWon": false,
    "ndaCandidate": "Jibi Pathickal",
    "ndaParty": "Twenty 20 Party",
    "ndaVotes": 22497,
    "ndaVotePct": 15.25,
    "totalVotes": 147529,
    "numCandidates": 6,
    "runnerUpName": "Basil Paul",
    "runnerUpParty": "Kerala Congress (M)",
    "runnerUpVotes": 46654
  },
  "77": {
    "csvName": "Kalamassery",
    "winnerName": "Adv. V E Abdul Gafoor",
    "winnerParty": "Indian Union Muslim League",
    "winnerVotes": 80606,
    "loserName": "Binu",
    "loserParty": "Bharath Dharma Jana Sena",
    "loserVotes": 14130,
    "margin": 66476,
    "officialMargin": 16312,
    "ndaWon": false,
    "ndaCandidate": "Binu",
    "ndaParty": "Bharath Dharma Jana Sena",
    "ndaVotes": 14130,
    "ndaVotePct": 8.65,
    "totalVotes": 163345,
    "numCandidates": 8,
    "runnerUpName": "P Rajeeve",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 64294
  },
  "84": {
    "csvName": "Kunnathunad",
    "winnerName": "V. P. Sajeendran",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 70292,
    "loserName": "Babu Divakaran",
    "loserParty": "Twenty 20 Party",
    "loserVotes": 40221,
    "margin": 30071,
    "officialMargin": 21283,
    "ndaWon": false,
    "ndaCandidate": "Babu Divakaran",
    "ndaParty": "Twenty 20 Party",
    "ndaVotes": 40221,
    "ndaVotePct": 24.97,
    "totalVotes": 161066,
    "numCandidates": 5,
    "runnerUpName": "Adv. P. V. Sreenijin",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 49009
  },
  "82": {
    "csvName": "Ernakulam",
    "winnerName": "T.J Vinod",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 61296,
    "loserName": "P.R. Sivasankar",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 19154,
    "margin": 42142,
    "officialMargin": 36163,
    "ndaWon": false,
    "ndaCandidate": "P.R. Sivasankar",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 19154,
    "ndaVotePct": 17.78,
    "totalVotes": 107732,
    "numCandidates": 5,
    "runnerUpName": "Sabu George",
    "runnerUpParty": "Independent",
    "runnerUpVotes": 25133
  },
  "86": {
    "csvName": "Muvattupuzha",
    "winnerName": "Dr. Mathew Kuzhalnadan",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 89914,
    "loserName": "Sunny Kadoothazhe",
    "loserParty": "Twenty 20 Party",
    "loserVotes": 9840,
    "margin": 80074,
    "officialMargin": 42829,
    "ndaWon": false,
    "ndaCandidate": "Sunny Kadoothazhe",
    "ndaParty": "Twenty 20 Party",
    "ndaVotes": 9840,
    "ndaVotePct": 6.64,
    "totalVotes": 148131,
    "numCandidates": 4,
    "runnerUpName": "N Arun",
    "runnerUpParty": "Communist Party of India",
    "runnerUpVotes": 47085
  },
  "83": {
    "csvName": "Thrikkakara",
    "winnerName": "Uma Thomas",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 83375,
    "loserName": "Akhil Raj (Akhil Marar)",
    "loserParty": "Twenty 20 Party",
    "loserVotes": 21424,
    "margin": 61951,
    "officialMargin": 50211,
    "ndaWon": false,
    "ndaCandidate": "Akhil Raj (Akhil Marar)",
    "ndaParty": "Twenty 20 Party",
    "ndaVotes": 21424,
    "ndaVotePct": 15.25,
    "totalVotes": 140472,
    "numCandidates": 5,
    "runnerUpName": "Adv. Pushpa Das",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 33164
  },
  "90": {
    "csvName": "Thodupuzha",
    "winnerName": "Apu John Joseph",
    "winnerParty": "Kerala Congress",
    "winnerVotes": 84796,
    "loserName": "Adv. Roy Varicattu",
    "loserParty": "Twenty 20 Party",
    "loserVotes": 12679,
    "margin": 72117,
    "officialMargin": 44291,
    "ndaWon": false,
    "ndaCandidate": "Adv. Roy Varicattu",
    "ndaParty": "Twenty 20 Party",
    "ndaVotes": 12679,
    "ndaVotePct": 8.67,
    "totalVotes": 146166,
    "numCandidates": 8,
    "runnerUpName": "Cyriac Chazhikadan",
    "runnerUpParty": "Kerala Congress (M)",
    "runnerUpVotes": 40505
  },
  "89": {
    "csvName": "Udumbanchola",
    "winnerName": "Adv. Senapathy Venu",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 64916,
    "loserName": "Adv. Sangeetha Viswanadhan",
    "loserParty": "Bharath Dharma Jana Sena",
    "loserVotes": 10157,
    "margin": 54759,
    "officialMargin": 20021,
    "ndaWon": false,
    "ndaCandidate": "Adv. Sangeetha Viswanadhan",
    "ndaParty": "Bharath Dharma Jana Sena",
    "ndaVotes": 10157,
    "ndaVotePct": 8.37,
    "totalVotes": 121356,
    "numCandidates": 4,
    "runnerUpName": "K.K. Jayachandran",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 44895
  },
  "81": {
    "csvName": "Thripunithura",
    "winnerName": "Deepak Joy",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 70256,
    "loserName": "Anjali .P. V",
    "loserParty": "Twenty 20 Party",
    "loserVotes": 29471,
    "margin": 40785,
    "officialMargin": 18468,
    "ndaWon": false,
    "ndaCandidate": "Anjali .P. V",
    "ndaParty": "Twenty 20 Party",
    "ndaVotes": 29471,
    "ndaVotePct": 19.07,
    "totalVotes": 154527,
    "numCandidates": 9,
    "runnerUpName": "K N Unnikrishnan",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 51788
  },
  "85": {
    "csvName": "Piravom",
    "winnerName": "Anoop Jacob",
    "winnerParty": "Kerala Congress (Jacob)",
    "winnerVotes": 89551,
    "loserName": "Jibi Abraham",
    "loserParty": "Twenty 20 Party",
    "loserVotes": 14861,
    "margin": 74690,
    "officialMargin": 44681,
    "ndaWon": false,
    "ndaCandidate": "Jibi Abraham",
    "ndaParty": "Twenty 20 Party",
    "ndaVotes": 14861,
    "ndaVotePct": 9.75,
    "totalVotes": 152386,
    "numCandidates": 7,
    "runnerUpName": "Sabu K Jacob",
    "runnerUpParty": "Kerala Congress (M)",
    "runnerUpVotes": 44870
  },
  "80": {
    "csvName": "Kochi",
    "winnerName": "Mohammed Shiyas",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 64318,
    "loserName": "Adv. Xavier Julappan",
    "loserParty": "Twenty 20 Party",
    "loserVotes": 11854,
    "margin": 52464,
    "officialMargin": 8188,
    "ndaWon": false,
    "ndaCandidate": "Adv. Xavier Julappan",
    "ndaParty": "Twenty 20 Party",
    "ndaVotes": 11854,
    "ndaVotePct": 8.82,
    "totalVotes": 134349,
    "numCandidates": 5,
    "runnerUpName": "K.J. Maxy",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 56130
  },
  "91": {
    "csvName": "Idukki",
    "winnerName": "Roy K Paulose",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 70562,
    "loserName": "Adv. Pratheesh Prabha",
    "loserParty": "Bharath Dharma Jana Sena",
    "loserVotes": 9410,
    "margin": 61152,
    "officialMargin": 23822,
    "ndaWon": false,
    "ndaCandidate": "Adv. Pratheesh Prabha",
    "ndaParty": "Bharath Dharma Jana Sena",
    "ndaVotes": 9410,
    "ndaVotePct": 7.33,
    "totalVotes": 128447,
    "numCandidates": 4,
    "runnerUpName": "Roshy Augustine",
    "runnerUpParty": "Kerala Congress (M)",
    "runnerUpVotes": 46740
  },
  "102": {
    "csvName": "Aroor",
    "winnerName": "Adv. Shanimol Osman",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 74469,
    "loserName": "Adv. P.S. Jyothis",
    "loserParty": "Bharath Dharma Jana Sena",
    "loserVotes": 20334,
    "margin": 54135,
    "officialMargin": 9324,
    "ndaWon": false,
    "ndaCandidate": "Adv. P.S. Jyothis",
    "ndaParty": "Bharath Dharma Jana Sena",
    "ndaVotes": 20334,
    "ndaVotePct": 12.55,
    "totalVotes": 161974,
    "numCandidates": 6,
    "runnerUpName": "Daleema",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 65145
  },
  "94": {
    "csvName": "Kaduthuruthy",
    "winnerName": "Adv.Mons Joseph",
    "winnerParty": "Kerala Congress",
    "winnerVotes": 70353,
    "loserName": "Suresh Ettikunnel",
    "loserParty": "Bharath Dharma Jana Sena",
    "loserVotes": 12228,
    "margin": 58125,
    "officialMargin": 31300,
    "ndaWon": false,
    "ndaCandidate": "Suresh Ettikunnel",
    "ndaParty": "Bharath Dharma Jana Sena",
    "ndaVotes": 12228,
    "ndaVotePct": 9.8,
    "totalVotes": 124752,
    "numCandidates": 7,
    "runnerUpName": "Nirmala Jimmy",
    "runnerUpParty": "Kerala Congress (M)",
    "runnerUpVotes": 39053
  },
  "95": {
    "csvName": "Vaikom",
    "winnerName": "K Binimon",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 52944,
    "loserName": "K Ajith",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 20297,
    "margin": 32647,
    "officialMargin": 1360,
    "ndaWon": false,
    "ndaCandidate": "K Ajith",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 20297,
    "ndaVotePct": 16.08,
    "totalVotes": 126238,
    "numCandidates": 7,
    "runnerUpName": "P Pradeep",
    "runnerUpParty": "Communist Party of India",
    "runnerUpVotes": 51584
  },
  "93": {
    "csvName": "Pala",
    "winnerName": "Mani C Kappen",
    "winnerParty": "Independent",
    "winnerVotes": 50799,
    "loserName": "Shone George",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 35304,
    "margin": 15495,
    "officialMargin": 2991,
    "ndaWon": false,
    "ndaCandidate": "Shone George",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 35304,
    "ndaVotePct": 25.99,
    "totalVotes": 135851,
    "numCandidates": 7,
    "runnerUpName": "Jose K Mani",
    "runnerUpParty": "Kerala Congress (M)",
    "runnerUpVotes": 47808
  },
  "103": {
    "csvName": "Cherthala",
    "winnerName": "P. Prasad",
    "winnerParty": "Communist Party of India",
    "winnerVotes": 83216,
    "loserName": "Adv. T.P. Anantharaj",
    "loserParty": "Bharath Dharma Jana Sena",
    "loserVotes": 17997,
    "margin": 65219,
    "officialMargin": 14489,
    "ndaWon": false,
    "ndaCandidate": "Adv. T.P. Anantharaj",
    "ndaParty": "Bharath Dharma Jana Sena",
    "ndaVotes": 17997,
    "ndaVotePct": 10.45,
    "totalVotes": 172221,
    "numCandidates": 7,
    "runnerUpName": "K.R. Rajendra Prasad",
    "runnerUpParty": "Indian National Congress",
    "runnerUpVotes": 68727
  },
  "92": {
    "csvName": "Peerumade",
    "winnerName": "Adv.Cyriac Thomas",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 69672,
    "loserName": "Ratheesh Varakumala",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 9218,
    "margin": 60454,
    "officialMargin": 27634,
    "ndaWon": false,
    "ndaCandidate": "Ratheesh Varakumala",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 9218,
    "ndaVotePct": 7.52,
    "totalVotes": 122652,
    "numCandidates": 5,
    "runnerUpName": "K Salimkumar",
    "runnerUpParty": "Communist Party of India",
    "runnerUpVotes": 42038
  },
  "101": {
    "csvName": "Poonjar",
    "winnerName": "Adv. Sebastian M.J",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 56900,
    "loserName": "P.C. George",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 36172,
    "margin": 20728,
    "officialMargin": 6693,
    "ndaWon": false,
    "ndaCandidate": "P.C. George",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 36172,
    "ndaVotePct": 24.98,
    "totalVotes": 144794,
    "numCandidates": 7,
    "runnerUpName": "Adv. Sebastian Kulathunkal",
    "runnerUpParty": "Kerala Congress (M)",
    "runnerUpVotes": 50207
  },
  "96": {
    "csvName": "Ettumanoor",
    "winnerName": "Nattakom Suresh",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 64077,
    "loserName": "Athira D Nair",
    "loserParty": "Twenty 20 Party",
    "loserVotes": 12975,
    "margin": 51102,
    "officialMargin": 19752,
    "ndaWon": false,
    "ndaCandidate": "Athira D Nair",
    "ndaParty": "Twenty 20 Party",
    "ndaVotes": 12975,
    "ndaVotePct": 10.56,
    "totalVotes": 122912,
    "numCandidates": 6,
    "runnerUpName": "V. N. Vasavan",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 44325
  },
  "98": {
    "csvName": "Puthuppally",
    "winnerName": "Adv. Chandy Oommen",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 84031,
    "loserName": "Raveendranath Vakathanam",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 11544,
    "margin": 72487,
    "officialMargin": 52907,
    "ndaWon": false,
    "ndaCandidate": "Raveendranath Vakathanam",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 11544,
    "ndaVotePct": 9.01,
    "totalVotes": 128180,
    "numCandidates": 6,
    "runnerUpName": "K. M. Radhakrishnan",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 31124
  },
  "104": {
    "csvName": "Alappuzha",
    "winnerName": "A.D Thomas",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 81065,
    "loserName": "M.J Job",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 15373,
    "margin": 65692,
    "officialMargin": 21015,
    "ndaWon": false,
    "ndaCandidate": "M.J Job",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 15373,
    "ndaVotePct": 9.75,
    "totalVotes": 157661,
    "numCandidates": 6,
    "runnerUpName": "P.P. Chitharanjan",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 60050
  },
  "97": {
    "csvName": "Kottayam",
    "winnerName": "Thiruvanchoor Radhakrishnan",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 68893,
    "loserName": "P Anilkumar",
    "loserParty": "Bharath Dharma Jana Sena",
    "loserVotes": 9726,
    "margin": 59167,
    "officialMargin": 35986,
    "ndaWon": false,
    "ndaCandidate": "P Anilkumar",
    "ndaParty": "Bharath Dharma Jana Sena",
    "ndaVotes": 9726,
    "ndaVotePct": 8.55,
    "totalVotes": 113747,
    "numCandidates": 6,
    "runnerUpName": "Adv. K. Anilkumar",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 32907
  },
  "100": {
    "csvName": "Kanjirappally",
    "winnerName": "Rony K Baby",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 56646,
    "loserName": "Adv. George Kurian",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 26984,
    "margin": 29662,
    "officialMargin": 5772,
    "ndaWon": false,
    "ndaCandidate": "Adv. George Kurian",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 26984,
    "ndaVotePct": 19.84,
    "totalVotes": 135988,
    "numCandidates": 4,
    "runnerUpName": "Dr. N. Jayaraj",
    "runnerUpParty": "Kerala Congress (M)",
    "runnerUpVotes": 50874
  },
  "106": {
    "csvName": "Kuttanad",
    "winnerName": "Reji Cheriyan",
    "winnerParty": "Kerala Congress",
    "winnerVotes": 56594,
    "loserName": "Santhosh Santhi",
    "loserParty": "Bharath Dharma Jana Sena",
    "loserVotes": 16932,
    "margin": 39662,
    "officialMargin": 20600,
    "ndaWon": false,
    "ndaCandidate": "Santhosh Santhi",
    "ndaParty": "Bharath Dharma Jana Sena",
    "ndaVotes": 16932,
    "ndaVotePct": 15.04,
    "totalVotes": 112560,
    "numCandidates": 8,
    "runnerUpName": "Thomas K. Thomas",
    "runnerUpParty": "Nationalist Congress Party - Sharadchandra Pawar",
    "runnerUpVotes": 35994
  },
  "99": {
    "csvName": "Changanassery",
    "winnerName": "Vinu Job Kuzhimannil",
    "winnerParty": "Kerala Congress",
    "winnerVotes": 55991,
    "loserName": "B Radhakrishna Menon",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 14803,
    "margin": 41188,
    "officialMargin": 8368,
    "ndaWon": false,
    "ndaCandidate": "B Radhakrishna Menon",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 14803,
    "ndaVotePct": 12.22,
    "totalVotes": 121150,
    "numCandidates": 10,
    "runnerUpName": "Adv. Job Maichil",
    "runnerUpParty": "Kerala Congress (M)",
    "runnerUpVotes": 47623
  },
  "105": {
    "csvName": "Ambalappuzha",
    "winnerName": "G. Sudhakaran",
    "winnerParty": "Independent",
    "winnerVotes": 75184,
    "loserName": "Arun Anirudhan",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 16348,
    "margin": 58836,
    "officialMargin": 27935,
    "ndaWon": false,
    "ndaCandidate": "Arun Anirudhan",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 16348,
    "ndaVotePct": 11.61,
    "totalVotes": 140781,
    "numCandidates": 4,
    "runnerUpName": "H. Salam",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 47249
  },
  "111": {
    "csvName": "Thiruvalla",
    "winnerName": "Adv. Varghese Mammen",
    "winnerParty": "Kerala Congress",
    "winnerVotes": 53224,
    "loserName": "Anoop Antony",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 43078,
    "margin": 10146,
    "officialMargin": 10146,
    "ndaWon": false,
    "ndaCandidate": "Anoop Antony",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 43078,
    "ndaVotePct": 30.61,
    "totalVotes": 140745,
    "numCandidates": 7,
    "runnerUpName": "Anoop Antony",
    "runnerUpParty": "Bharatiya Janata Party",
    "runnerUpVotes": 43078
  },
  "114": {
    "csvName": "Konni",
    "winnerName": "Adv K U Jenish Kumar",
    "winnerParty": "Communist Party of India (Marxist)",
    "winnerVotes": 60380,
    "loserName": "Sundaresan T P",
    "loserParty": "Bharath Dharma Jana Sena",
    "loserVotes": 15278,
    "margin": 45102,
    "officialMargin": 1838,
    "ndaWon": false,
    "ndaCandidate": "Sundaresan T P",
    "ndaParty": "Bharath Dharma Jana Sena",
    "ndaVotes": 15278,
    "ndaVotePct": 11.28,
    "totalVotes": 135405,
    "numCandidates": 4,
    "runnerUpName": "Prof Satheesh Kochuparambil",
    "runnerUpParty": "Indian National Congress",
    "runnerUpVotes": 58542
  },
  "112": {
    "csvName": "Ranni",
    "winnerName": "Adv. Pazhakulam Madhu",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 54652,
    "loserName": "Thomas K Samuel (Blesson)",
    "loserParty": "Twenty 20 Party",
    "loserVotes": 17993,
    "margin": 36659,
    "officialMargin": 4344,
    "ndaWon": false,
    "ndaCandidate": "Thomas K Samuel (Blesson)",
    "ndaParty": "Twenty 20 Party",
    "ndaVotes": 17993,
    "ndaVotePct": 14.53,
    "totalVotes": 123843,
    "numCandidates": 4,
    "runnerUpName": "Adv. Pramod Narayan",
    "runnerUpParty": "Kerala Congress (M)",
    "runnerUpVotes": 50308
  },
  "113": {
    "csvName": "Aranmula",
    "winnerName": "Abin Varkey Kodiyattu",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 70083,
    "loserName": "Kummanam Rajasekharan",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 34983,
    "margin": 35100,
    "officialMargin": 18985,
    "ndaWon": false,
    "ndaCandidate": "Kummanam Rajasekharan",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 34983,
    "ndaVotePct": 22.22,
    "totalVotes": 157450,
    "numCandidates": 6,
    "runnerUpName": "Veena George",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 51098
  },
  "107": {
    "csvName": "Haripad",
    "winnerName": "Ramesh Chennithala",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 68184,
    "loserName": "Sandheep Vaachaspathi",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 31022,
    "margin": 37162,
    "officialMargin": 23377,
    "ndaWon": false,
    "ndaCandidate": "Sandheep Vaachaspathi",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 31022,
    "ndaVotePct": 21.42,
    "totalVotes": 144837,
    "numCandidates": 6,
    "runnerUpName": "T.T. Jismon",
    "runnerUpParty": "Communist Party of India",
    "runnerUpVotes": 44807
  },
  "110": {
    "csvName": "Chengannur",
    "winnerName": "Saji Cherian",
    "winnerParty": "Communist Party of India (Marxist)",
    "winnerVotes": 57859,
    "loserName": "M. V. Gopakumar",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 30942,
    "margin": 26917,
    "officialMargin": 10292,
    "ndaWon": false,
    "ndaCandidate": "M. V. Gopakumar",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 30942,
    "ndaVotePct": 22.51,
    "totalVotes": 137435,
    "numCandidates": 4,
    "runnerUpName": "Adv. Abi Kuriakose",
    "runnerUpParty": "Indian National Congress",
    "runnerUpVotes": 47567
  },
  "109": {
    "csvName": "Mavelikkara",
    "winnerName": "M.S. Arun Kumar",
    "winnerParty": "Communist Party of India (Marxist)",
    "winnerVotes": 67180,
    "loserName": "K. Ajimon",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 23200,
    "margin": 43980,
    "officialMargin": 15736,
    "ndaWon": false,
    "ndaCandidate": "K. Ajimon",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 23200,
    "ndaVotePct": 16.26,
    "totalVotes": 142667,
    "numCandidates": 4,
    "runnerUpName": "Adv. Muthara Raj",
    "runnerUpParty": "Indian National Congress",
    "runnerUpVotes": 51444
  },
  "108": {
    "csvName": "Kayamkulam",
    "winnerName": "Adv. M. Liju",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 76651,
    "loserName": "Thampi Mettuthara",
    "loserParty": "Bharath Dharma Jana Sena",
    "loserVotes": 16973,
    "margin": 59678,
    "officialMargin": 15572,
    "ndaWon": false,
    "ndaCandidate": "Thampi Mettuthara",
    "ndaParty": "Bharath Dharma Jana Sena",
    "ndaVotes": 16973,
    "ndaVotePct": 10.92,
    "totalVotes": 155399,
    "numCandidates": 3,
    "runnerUpName": "Adv. U. Prathibha",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 61079
  },
  "115": {
    "csvName": "Adoor",
    "winnerName": "Advocate C V Santhakumar",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 66153,
    "loserName": "Adv. Pandalam Prathapan",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 26337,
    "margin": 39816,
    "officialMargin": 10332,
    "ndaWon": false,
    "ndaCandidate": "Adv. Pandalam Prathapan",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 26337,
    "ndaVotePct": 17.6,
    "totalVotes": 149670,
    "numCandidates": 4,
    "runnerUpName": "Priji Kannan",
    "runnerUpParty": "Communist Party of India",
    "runnerUpVotes": 55821
  },
  "120": {
    "csvName": "Pathanapuram",
    "winnerName": "Jyothi Kumar Chamakkala",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 68275,
    "loserName": "Anil Pillai",
    "loserParty": "Twenty 20 Party",
    "loserVotes": 7031,
    "margin": 61244,
    "officialMargin": 8310,
    "ndaWon": false,
    "ndaCandidate": "Anil Pillai",
    "ndaParty": "Twenty 20 Party",
    "ndaVotes": 7031,
    "ndaVotePct": 5.11,
    "totalVotes": 137623,
    "numCandidates": 7,
    "runnerUpName": "K B Ganesh Kumar",
    "runnerUpParty": "Kerala Congress (B)",
    "runnerUpVotes": 59965
  },
  "116": {
    "csvName": "Karunagappally",
    "winnerName": "C.R. Mahesh",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 82593,
    "loserName": "V.S. Jithin Dev",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 32121,
    "margin": 50472,
    "officialMargin": 26618,
    "ndaWon": false,
    "ndaCandidate": "V.S. Jithin Dev",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 32121,
    "ndaVotePct": 18.6,
    "totalVotes": 172736,
    "numCandidates": 5,
    "runnerUpName": "Adv. M.S. Thara",
    "runnerUpParty": "Communist Party of India",
    "runnerUpVotes": 55975
  },
  "118": {
    "csvName": "Kunnathur",
    "winnerName": "Ullas Kovur",
    "winnerParty": "Revolutionary Socialist Party",
    "winnerVotes": 81488,
    "loserName": "Raji Prasad",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 24841,
    "margin": 56647,
    "officialMargin": 25314,
    "ndaWon": false,
    "ndaCandidate": "Raji Prasad",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 24841,
    "ndaVotePct": 15.14,
    "totalVotes": 164101,
    "numCandidates": 5,
    "runnerUpName": "Kovoor Kunjumon",
    "runnerUpParty": "Kerala Revolutionary Socialist Party (Leninist- Marxist)",
    "runnerUpVotes": 56174
  },
  "121": {
    "csvName": "Punalur",
    "winnerName": "C. Ajayaprasad",
    "winnerParty": "Communist Party of India",
    "winnerVotes": 71944,
    "loserName": "Adv. Reghunadh Kamukumchery",
    "loserParty": "Twenty 20 Party",
    "loserVotes": 15393,
    "margin": 56551,
    "officialMargin": 21529,
    "ndaWon": false,
    "ndaCandidate": "Adv. Reghunadh Kamukumchery",
    "ndaParty": "Twenty 20 Party",
    "ndaVotes": 15393,
    "ndaVotePct": 10.8,
    "totalVotes": 142556,
    "numCandidates": 6,
    "runnerUpName": "Noushad Younus",
    "runnerUpParty": "Indian Union Muslim League",
    "runnerUpVotes": 50415
  },
  "119": {
    "csvName": "Kottarakkara",
    "winnerName": "K.N. Balagopal",
    "winnerParty": "Communist Party of India (Marxist)",
    "winnerVotes": 63926,
    "loserName": "R. Resmi",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 20664,
    "margin": 43262,
    "officialMargin": 1012,
    "ndaWon": false,
    "ndaCandidate": "R. Resmi",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 20664,
    "ndaVotePct": 13.88,
    "totalVotes": 148854,
    "numCandidates": 6,
    "runnerUpName": "Adv. P. Aisha Potty",
    "runnerUpParty": "Indian National Congress",
    "runnerUpVotes": 62914
  },
  "117": {
    "csvName": "Chavara",
    "winnerName": "Shibu Baby John",
    "winnerParty": "Revolutionary Socialist Party",
    "winnerVotes": 74308,
    "loserName": "K.R. Rajesh",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 11012,
    "margin": 63296,
    "officialMargin": 18573,
    "ndaWon": false,
    "ndaCandidate": "K.R. Rajesh",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 11012,
    "ndaVotePct": 7.74,
    "totalVotes": 142344,
    "numCandidates": 3,
    "runnerUpName": "Dr. Sujith Vijayanpillai",
    "runnerUpParty": "Independent",
    "runnerUpVotes": 55735
  },
  "123": {
    "csvName": "Kundara",
    "winnerName": "P. C. Vishnunadh",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 87862,
    "loserName": "Dr. Robin Radhakrishnan",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 18996,
    "margin": 68866,
    "officialMargin": 32564,
    "ndaWon": false,
    "ndaCandidate": "Dr. Robin Radhakrishnan",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 18996,
    "ndaVotePct": 11.55,
    "totalVotes": 164414,
    "numCandidates": 6,
    "runnerUpName": "S. L. Sajikumar",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 55298
  },
  "124": {
    "csvName": "Kollam",
    "winnerName": "Adv. Bindhu Krishna",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 63416,
    "loserName": "Dr. Prathap Kumar N",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 18537,
    "margin": 44879,
    "officialMargin": 16830,
    "ndaWon": false,
    "ndaCandidate": "Dr. Prathap Kumar N",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 18537,
    "ndaVotePct": 14.29,
    "totalVotes": 129690,
    "numCandidates": 5,
    "runnerUpName": "S. Jayamohan",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 46586
  },
  "122": {
    "csvName": "Chadayamangalam",
    "winnerName": "M. M. Naseer",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 68281,
    "loserName": "R.S. Arunraj",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 20971,
    "margin": 47310,
    "officialMargin": 7486,
    "ndaWon": false,
    "ndaCandidate": "R.S. Arunraj",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 20971,
    "ndaVotePct": 13.68,
    "totalVotes": 153260,
    "numCandidates": 6,
    "runnerUpName": "J. Chinchurani",
    "runnerUpParty": "Communist Party of India",
    "runnerUpVotes": 60795
  },
  "125": {
    "csvName": "Eravipuram",
    "winnerName": "Adv. Vishnu Mohan",
    "winnerParty": "Revolutionary Socialist Party",
    "winnerVotes": 64383,
    "loserName": "Sajee D Anand",
    "loserParty": "Bharath Dharma Jana Sena",
    "loserVotes": 10469,
    "margin": 53914,
    "officialMargin": 8803,
    "ndaWon": false,
    "ndaCandidate": "Sajee D Anand",
    "ndaParty": "Bharath Dharma Jana Sena",
    "ndaVotes": 10469,
    "ndaVotePct": 7.91,
    "totalVotes": 132384,
    "numCandidates": 5,
    "runnerUpName": "M. Noushad",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 55580
  },
  "126": {
    "csvName": "Chathannoor",
    "winnerName": "B.B. Gopakumar",
    "winnerParty": "Bharatiya Janata Party",
    "winnerVotes": 51923,
    "loserName": "Adv. R. Rajendran",
    "loserParty": "Communist Party of India",
    "loserVotes": 47525,
    "margin": 4398,
    "officialMargin": 4398,
    "ndaWon": true,
    "ndaCandidate": "B.B. Gopakumar",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 51923,
    "ndaVotePct": 38.04,
    "totalVotes": 136507,
    "numCandidates": 5,
    "runnerUpName": "Adv. R. Rajendran",
    "runnerUpParty": "Communist Party of India",
    "runnerUpVotes": 47525
  },
  "127": {
    "csvName": "Varkala",
    "winnerName": "Adv. V Joy",
    "winnerParty": "Communist Party of India (Marxist)",
    "winnerVotes": 55365,
    "loserName": "Adv. Smitha Sundaresan",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 27400,
    "margin": 27965,
    "officialMargin": 2050,
    "ndaWon": false,
    "ndaCandidate": "Adv. Smitha Sundaresan",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 27400,
    "ndaVotePct": 19.82,
    "totalVotes": 138231,
    "numCandidates": 9,
    "runnerUpName": "Varkala Kahar",
    "runnerUpParty": "Indian National Congress",
    "runnerUpVotes": 53315
  },
  "131": {
    "csvName": "Vamanapuram",
    "winnerName": "Muhammed Sudheersha S",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 73590,
    "loserName": "Venu",
    "loserParty": "Bharath Dharma Jana Sena",
    "loserVotes": 12093,
    "margin": 61497,
    "officialMargin": 12185,
    "ndaWon": false,
    "ndaCandidate": "Venu",
    "ndaParty": "Bharath Dharma Jana Sena",
    "ndaVotes": 12093,
    "ndaVotePct": 8.11,
    "totalVotes": 149082,
    "numCandidates": 6,
    "runnerUpName": "Muraleedharan Nair D K",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 61405
  },
  "128": {
    "csvName": "Attingal",
    "winnerName": "O. S. Ambika",
    "winnerParty": "Communist Party of India (Marxist)",
    "winnerVotes": 59163,
    "loserName": "Adv. P Sudheer",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 45788,
    "margin": 13375,
    "officialMargin": 13375,
    "ndaWon": false,
    "ndaCandidate": "Adv. P Sudheer",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 45788,
    "ndaVotePct": 30.54,
    "totalVotes": 149916,
    "numCandidates": 6,
    "runnerUpName": "Adv. P Sudheer",
    "runnerUpParty": "Bharatiya Janata Party",
    "runnerUpVotes": 45788
  },
  "129": {
    "csvName": "Chirayinkeezhu",
    "winnerName": "Ramya Haridas",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 56833,
    "loserName": "B. S. Anoop",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 32920,
    "margin": 23913,
    "officialMargin": 1422,
    "ndaWon": false,
    "ndaCandidate": "B. S. Anoop",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 32920,
    "ndaVotePct": 22.31,
    "totalVotes": 147566,
    "numCandidates": 5,
    "runnerUpName": "Manoj Edamana",
    "runnerUpParty": "Communist Party of India",
    "runnerUpVotes": 55411
  },
  "136": {
    "csvName": "Aruvikkara",
    "winnerName": "Adv. G. Steephen",
    "winnerParty": "Communist Party of India (Marxist)",
    "winnerVotes": 61907,
    "loserName": "Vivek Gopan",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 23760,
    "margin": 38147,
    "officialMargin": 2843,
    "ndaWon": false,
    "ndaCandidate": "Vivek Gopan",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 23760,
    "ndaVotePct": 16.18,
    "totalVotes": 146878,
    "numCandidates": 7,
    "runnerUpName": "V. S. Sivakumar",
    "runnerUpParty": "Indian National Congress",
    "runnerUpVotes": 59064
  },
  "130": {
    "csvName": "Nedumangad",
    "winnerName": "G R Anil",
    "winnerParty": "Communist Party of India",
    "winnerVotes": 69206,
    "loserName": "Yuvraj Gokul",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 38999,
    "margin": 30207,
    "officialMargin": 21583,
    "ndaWon": false,
    "ndaCandidate": "Yuvraj Gokul",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 38999,
    "ndaVotePct": 24.54,
    "totalVotes": 158894,
    "numCandidates": 9,
    "runnerUpName": "Meenankal Kumar",
    "runnerUpParty": "Indian National Congress",
    "runnerUpVotes": 47623
  },
  "132": {
    "csvName": "Kazhakoottam",
    "winnerName": "V. Muraleedharan",
    "winnerParty": "Bharatiya Janata Party",
    "winnerVotes": 46564,
    "loserName": "Kadakampally Surendran",
    "loserParty": "Communist Party of India (Marxist)",
    "loserVotes": 46136,
    "margin": 428,
    "officialMargin": 428,
    "ndaWon": true,
    "ndaCandidate": "V. Muraleedharan",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 46564,
    "ndaVotePct": 35.39,
    "totalVotes": 131587,
    "numCandidates": 7,
    "runnerUpName": "Kadakampally Surendran",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 46136
  },
  "137": {
    "csvName": "Parassala",
    "winnerName": "C K Hareendran",
    "winnerParty": "Communist Party of India (Marxist)",
    "winnerVotes": 69149,
    "loserName": "Adv. Gireesh Neyyar",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 29919,
    "margin": 39230,
    "officialMargin": 15013,
    "ndaWon": false,
    "ndaCandidate": "Adv. Gireesh Neyyar",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 29919,
    "ndaVotePct": 19.3,
    "totalVotes": 155008,
    "numCandidates": 8,
    "runnerUpName": "Neyyattinkara Sanal",
    "runnerUpParty": "Indian National Congress",
    "runnerUpVotes": 54136
  },
  "133": {
    "csvName": "Vattiyoorkavu",
    "winnerName": "K. Muraleedharan",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 48338,
    "loserName": "R. Sreelekha",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 37213,
    "margin": 11125,
    "officialMargin": 5425,
    "ndaWon": false,
    "ndaCandidate": "R. Sreelekha",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 37213,
    "ndaVotePct": 28.68,
    "totalVotes": 129765,
    "numCandidates": 8,
    "runnerUpName": "Adv. V.K Prasanth",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 42913
  },
  "138": {
    "csvName": "Kattakada",
    "winnerName": "M. R. Baiju",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 56846,
    "loserName": "P. K. Krishnadas",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 38231,
    "margin": 18615,
    "officialMargin": 7136,
    "ndaWon": false,
    "ndaCandidate": "P. K. Krishnadas",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 38231,
    "ndaVotePct": 26.14,
    "totalVotes": 146244,
    "numCandidates": 5,
    "runnerUpName": "Adv. I. B. Satheesh",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 49710
  },
  "134": {
    "csvName": "Thiruvananthapuram",
    "winnerName": "C P John",
    "winnerParty": "Communist Marxist Party Kerala State Committee",
    "winnerVotes": 45586,
    "loserName": "Karamana Jayan",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 35125,
    "margin": 10461,
    "officialMargin": 9863,
    "ndaWon": false,
    "ndaCandidate": "Karamana Jayan",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 35125,
    "ndaVotePct": 29.15,
    "totalVotes": 120488,
    "numCandidates": 11,
    "runnerUpName": "Sudhir Karamana",
    "runnerUpParty": "Independent",
    "runnerUpVotes": 35723
  },
  "135": {
    "csvName": "Nemom",
    "winnerName": "Rajeev Chandrasekhar",
    "winnerParty": "Bharatiya Janata Party",
    "winnerVotes": 57192,
    "loserName": "V Sivankutty",
    "loserParty": "Communist Party of India (Marxist)",
    "loserVotes": 52214,
    "margin": 4978,
    "officialMargin": 4978,
    "ndaWon": true,
    "ndaCandidate": "Rajeev Chandrasekhar",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 57192,
    "ndaVotePct": 40.75,
    "totalVotes": 140355,
    "numCandidates": 10,
    "runnerUpName": "V Sivankutty",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 52214
  },
  "140": {
    "csvName": "Neyyattinkara",
    "winnerName": "N. Shakthan",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 58760,
    "loserName": "Chenkal Rajasekharan",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 21858,
    "margin": 36902,
    "officialMargin": 6966,
    "ndaWon": false,
    "ndaCandidate": "Chenkal Rajasekharan",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 21858,
    "ndaVotePct": 16.36,
    "totalVotes": 133616,
    "numCandidates": 5,
    "runnerUpName": "K. Ansalan",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 51794
  },
  "139": {
    "csvName": "Kovalam",
    "winnerName": "Adv. M.Vincent",
    "winnerParty": "Indian National Congress",
    "winnerVotes": 79661,
    "loserName": "Kovalam.T.N.Suresh",
    "loserParty": "Bharatiya Janata Party",
    "loserVotes": 25380,
    "margin": 54281,
    "officialMargin": 32709,
    "ndaWon": false,
    "ndaCandidate": "Kovalam.T.N.Suresh",
    "ndaParty": "Bharatiya Janata Party",
    "ndaVotes": 25380,
    "ndaVotePct": 16.35,
    "totalVotes": 155237,
    "numCandidates": 9,
    "runnerUpName": "Bhagath Rufus",
    "runnerUpParty": "Independent",
    "runnerUpVotes": 46952
  },
  "87": {
    "csvName": "Kothamangalam",
    "winnerName": "Shibu Theckumpuram",
    "winnerParty": "Kerala Congress",
    "winnerVotes": 73479,
    "loserName": "Aji Narayanan",
    "loserParty": "Bharath Dharma Jana Sena",
    "loserVotes": 7046,
    "margin": 66433,
    "officialMargin": 16859,
    "ndaWon": false,
    "ndaCandidate": "Aji Narayanan",
    "ndaParty": "Bharath Dharma Jana Sena",
    "ndaVotes": 7046,
    "ndaVotePct": 5.07,
    "totalVotes": 139091,
    "numCandidates": 7,
    "runnerUpName": "Antony John",
    "runnerUpParty": "Communist Party of India (Marxist)",
    "runnerUpVotes": 56620
  }
};
